version: "3.7"

services:
  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    command: python /usr/src/om54/library/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/om54
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:



